package com.gxtc.yyj.newyin.mvp.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gxtc.yyj.newyin.mvp.greendao.bean.Explore;
import com.gxtc.yyj.newyin.mvp.greendao.bean.User;

import com.gxtc.yyj.newyin.mvp.greendao.dao.ExploreDao;
import com.gxtc.yyj.newyin.mvp.greendao.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exploreDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ExploreDao exploreDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exploreDaoConfig = daoConfigMap.get(ExploreDao.class).clone();
        exploreDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        exploreDao = new ExploreDao(exploreDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Explore.class, exploreDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        exploreDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ExploreDao getExploreDao() {
        return exploreDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
